//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Localization.Resources.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audiences: {0} are occupied.
        /// </summary>
        internal static string errors_AudiencesOccupied {
            get {
                return ResourceManager.GetString("errors.AudiencesOccupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t  delete a published schedule.
        /// </summary>
        internal static string errors_DeletePublishedSchedule {
            get {
                return ResourceManager.GetString("errors.DeletePublishedSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum member not found.
        /// </summary>
        internal static string errors_EnumNotFound {
            get {
                return ResourceManager.GetString("errors.EnumNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups: {0} are busy.
        /// </summary>
        internal static string errors_GroupsBusy {
            get {
                return ResourceManager.GetString("errors.GroupsBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error.
        /// </summary>
        internal static string errors_Internal {
            get {
                return ResourceManager.GetString("errors.Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password or email.
        /// </summary>
        internal static string errors_InvalidCredentials {
            get {
                return ResourceManager.GetString("errors.InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity {0} not found.
        /// </summary>
        internal static string errors_NotFound {
            get {
                return ResourceManager.GetString("errors.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule is already published.
        /// </summary>
        internal static string errors_SchedulePublished {
            get {
                return ResourceManager.GetString("errors.SchedulePublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teachers: {0} are busy.
        /// </summary>
        internal static string errors_TeachersBusy {
            get {
                return ResourceManager.GetString("errors.TeachersBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to signup user: {0}.
        /// </summary>
        internal static string errors_UnableToSignup {
            get {
                return ResourceManager.GetString("errors.UnableToSignup", resourceCulture);
            }
        }
    }
}
