version: "3.8"

services:
  api:
    build:
      dockerfile: api.dockerfile
    ports:
      - "5000:5000"
    environment:
      ConnectionStrings__postgres: "Host=db;Username=postgres;Password=postgres;Database=my_bsnu"
  db:
    build:
      dockerfile: db.dockerfile
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "my_bsnu"

volumes:
  db_volume: